name: PR Title Lint
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  pr-title-lint:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Hello world action step
        uses: ./.github/actions