name: PR

on: 
  pull_request:
    types: [opened, edited]
  push:
    branches-ignore:
      - 'main'

jobs:
  checkTitleFormat:
    runs-on: ubuntu-latest

    steps:
      - name: Check Title Format
        uses: actions/checkout@main
      - name: Run Title Format Check
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "PR title: $PR_TITLE"
